//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  team: Team;
  teamConnection: TeamConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
  customer: Customer;
  customerConnection: CustomerConnection;
  integration: Integration;
  integrationConnection: IntegrationConnection;
  office: Office;
  officeConnection: OfficeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};


export type QueryCustomerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCustomerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CustomerFilter>;
};


export type QueryIntegrationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryIntegrationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IntegrationFilter>;
};


export type QueryOfficeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOfficeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OfficeFilter>;
};

export type DocumentFilter = {
  team?: InputMaybe<TeamFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
  customer?: InputMaybe<CustomerFilter>;
  integration?: InputMaybe<IntegrationFilter>;
  office?: InputMaybe<OfficeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Team | Testimonial | Customer | Integration | Office | Folder;

export type Team = Node & Document & {
  __typename?: 'Team';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TeamFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  photo?: InputMaybe<ImageFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type TestimonialAuthors = {
  __typename?: 'TestimonialAuthors';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  company: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  previewQuote?: Maybe<Scalars['String']['output']>;
  authors?: Maybe<Array<Maybe<TestimonialAuthors>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialAuthorsFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
};

export type TestimonialFilter = {
  company?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  logo?: InputMaybe<ImageFilter>;
  photo?: InputMaybe<ImageFilter>;
  quote?: InputMaybe<StringFilter>;
  previewQuote?: InputMaybe<StringFilter>;
  authors?: InputMaybe<TestimonialAuthorsFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type Customer = Node & Document & {
  __typename?: 'Customer';
  name: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CustomerFilter = {
  name?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type CustomerConnectionEdges = {
  __typename?: 'CustomerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Customer>;
};

export type CustomerConnection = Connection & {
  __typename?: 'CustomerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CustomerConnectionEdges>>>;
};

export type Integration = Node & Document & {
  __typename?: 'Integration';
  name: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type IntegrationFilter = {
  name?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type IntegrationConnectionEdges = {
  __typename?: 'IntegrationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Integration>;
};

export type IntegrationConnection = Connection & {
  __typename?: 'IntegrationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<IntegrationConnectionEdges>>>;
};

export type Office = Node & Document & {
  __typename?: 'Office';
  city: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  lat?: Maybe<Scalars['Float']['output']>;
  lng?: Maybe<Scalars['Float']['output']>;
  mapsUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OfficeFilter = {
  city?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  lat?: InputMaybe<NumberFilter>;
  lng?: InputMaybe<NumberFilter>;
  mapsUrl?: InputMaybe<StringFilter>;
};

export type OfficeConnectionEdges = {
  __typename?: 'OfficeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Office>;
};

export type OfficeConnection = Connection & {
  __typename?: 'OfficeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OfficeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTeam: Team;
  createTeam: Team;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
  updateCustomer: Customer;
  createCustomer: Customer;
  updateIntegration: Integration;
  createIntegration: Integration;
  updateOffice: Office;
  createOffice: Office;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationUpdateCustomerArgs = {
  relativePath: Scalars['String']['input'];
  params: CustomerMutation;
};


export type MutationCreateCustomerArgs = {
  relativePath: Scalars['String']['input'];
  params: CustomerMutation;
};


export type MutationUpdateIntegrationArgs = {
  relativePath: Scalars['String']['input'];
  params: IntegrationMutation;
};


export type MutationCreateIntegrationArgs = {
  relativePath: Scalars['String']['input'];
  params: IntegrationMutation;
};


export type MutationUpdateOfficeArgs = {
  relativePath: Scalars['String']['input'];
  params: OfficeMutation;
};


export type MutationCreateOfficeArgs = {
  relativePath: Scalars['String']['input'];
  params: OfficeMutation;
};

export type DocumentUpdateMutation = {
  team?: InputMaybe<TeamMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  customer?: InputMaybe<CustomerMutation>;
  integration?: InputMaybe<IntegrationMutation>;
  office?: InputMaybe<OfficeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  team?: InputMaybe<TeamMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  customer?: InputMaybe<CustomerMutation>;
  integration?: InputMaybe<IntegrationMutation>;
  office?: InputMaybe<OfficeMutation>;
};

export type TeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialAuthorsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialMutation = {
  company?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  previewQuote?: InputMaybe<Scalars['String']['input']>;
  authors?: InputMaybe<Array<InputMaybe<TestimonialAuthorsMutation>>>;
};

export type CustomerMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type IntegrationMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type OfficeMutation = {
  city?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  lat?: InputMaybe<Scalars['Float']['input']>;
  lng?: InputMaybe<Scalars['Float']['input']>;
  mapsUrl?: InputMaybe<Scalars['String']['input']>;
};

export type TeamPartsFragment = { __typename: 'Team', name: string, role: string, order?: number | null, photo?: string | null, phone?: string | null, email?: string | null, linkedin?: string | null };

export type TestimonialPartsFragment = { __typename: 'Testimonial', company: string, order?: number | null, logo?: string | null, photo?: string | null, quote?: string | null, previewQuote?: string | null, authors?: Array<{ __typename: 'TestimonialAuthors', name?: string | null, title?: string | null } | null> | null };

export type CustomerPartsFragment = { __typename: 'Customer', name: string, order?: number | null, logo?: string | null };

export type IntegrationPartsFragment = { __typename: 'Integration', name: string, order?: number | null, logo?: string | null };

export type OfficePartsFragment = { __typename: 'Office', city: string, order?: number | null, lat?: number | null, lng?: number | null, mapsUrl?: string | null };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, name: string, role: string, order?: number | null, photo?: string | null, phone?: string | null, email?: string | null, linkedin?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, name: string, role: string, order?: number | null, photo?: string | null, phone?: string | null, email?: string | null, linkedin?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialQuery = { __typename?: 'Query', testimonial: { __typename: 'Testimonial', id: string, company: string, order?: number | null, logo?: string | null, photo?: string | null, quote?: string | null, previewQuote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, authors?: Array<{ __typename: 'TestimonialAuthors', name?: string | null, title?: string | null } | null> | null } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
}>;


export type TestimonialConnectionQuery = { __typename?: 'Query', testimonialConnection: { __typename?: 'TestimonialConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialConnectionEdges', cursor: string, node?: { __typename: 'Testimonial', id: string, company: string, order?: number | null, logo?: string | null, photo?: string | null, quote?: string | null, previewQuote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, authors?: Array<{ __typename: 'TestimonialAuthors', name?: string | null, title?: string | null } | null> | null } | null } | null> | null } };

export type CustomerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CustomerQuery = { __typename?: 'Query', customer: { __typename: 'Customer', id: string, name: string, order?: number | null, logo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CustomerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CustomerFilter>;
}>;


export type CustomerConnectionQuery = { __typename?: 'Query', customerConnection: { __typename?: 'CustomerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CustomerConnectionEdges', cursor: string, node?: { __typename: 'Customer', id: string, name: string, order?: number | null, logo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type IntegrationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type IntegrationQuery = { __typename?: 'Query', integration: { __typename: 'Integration', id: string, name: string, order?: number | null, logo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type IntegrationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<IntegrationFilter>;
}>;


export type IntegrationConnectionQuery = { __typename?: 'Query', integrationConnection: { __typename?: 'IntegrationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'IntegrationConnectionEdges', cursor: string, node?: { __typename: 'Integration', id: string, name: string, order?: number | null, logo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type OfficeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OfficeQuery = { __typename?: 'Query', office: { __typename: 'Office', id: string, city: string, order?: number | null, lat?: number | null, lng?: number | null, mapsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type OfficeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OfficeFilter>;
}>;


export type OfficeConnectionQuery = { __typename?: 'Query', officeConnection: { __typename?: 'OfficeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OfficeConnectionEdges', cursor: string, node?: { __typename: 'Office', id: string, city: string, order?: number | null, lat?: number | null, lng?: number | null, mapsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  name
  role
  order
  photo
  phone
  email
  linkedin
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  company
  order
  logo
  photo
  quote
  previewQuote
  authors {
    __typename
    name
    title
  }
}
    `;
export const CustomerPartsFragmentDoc = gql`
    fragment CustomerParts on Customer {
  __typename
  name
  order
  logo
}
    `;
export const IntegrationPartsFragmentDoc = gql`
    fragment IntegrationParts on Integration {
  __typename
  name
  order
  logo
}
    `;
export const OfficePartsFragmentDoc = gql`
    fragment OfficeParts on Office {
  __typename
  city
  order
  lat
  lng
  mapsUrl
}
    `;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const CustomerDocument = gql`
    query customer($relativePath: String!) {
  customer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CustomerParts
  }
}
    ${CustomerPartsFragmentDoc}`;
export const CustomerConnectionDocument = gql`
    query customerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CustomerFilter) {
  customerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CustomerParts
      }
    }
  }
}
    ${CustomerPartsFragmentDoc}`;
export const IntegrationDocument = gql`
    query integration($relativePath: String!) {
  integration(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...IntegrationParts
  }
}
    ${IntegrationPartsFragmentDoc}`;
export const IntegrationConnectionDocument = gql`
    query integrationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: IntegrationFilter) {
  integrationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...IntegrationParts
      }
    }
  }
}
    ${IntegrationPartsFragmentDoc}`;
export const OfficeDocument = gql`
    query office($relativePath: String!) {
  office(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OfficeParts
  }
}
    ${OfficePartsFragmentDoc}`;
export const OfficeConnectionDocument = gql`
    query officeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OfficeFilter) {
  officeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OfficeParts
      }
    }
  }
}
    ${OfficePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      },
    customer(variables: CustomerQueryVariables, options?: C): Promise<{data: CustomerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CustomerQueryVariables, query: string}> {
        return requester<{data: CustomerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CustomerQueryVariables, query: string}, CustomerQueryVariables>(CustomerDocument, variables, options);
      },
    customerConnection(variables?: CustomerConnectionQueryVariables, options?: C): Promise<{data: CustomerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CustomerConnectionQueryVariables, query: string}> {
        return requester<{data: CustomerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CustomerConnectionQueryVariables, query: string}, CustomerConnectionQueryVariables>(CustomerConnectionDocument, variables, options);
      },
    integration(variables: IntegrationQueryVariables, options?: C): Promise<{data: IntegrationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IntegrationQueryVariables, query: string}> {
        return requester<{data: IntegrationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IntegrationQueryVariables, query: string}, IntegrationQueryVariables>(IntegrationDocument, variables, options);
      },
    integrationConnection(variables?: IntegrationConnectionQueryVariables, options?: C): Promise<{data: IntegrationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IntegrationConnectionQueryVariables, query: string}> {
        return requester<{data: IntegrationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: IntegrationConnectionQueryVariables, query: string}, IntegrationConnectionQueryVariables>(IntegrationConnectionDocument, variables, options);
      },
    office(variables: OfficeQueryVariables, options?: C): Promise<{data: OfficeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OfficeQueryVariables, query: string}> {
        return requester<{data: OfficeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OfficeQueryVariables, query: string}, OfficeQueryVariables>(OfficeDocument, variables, options);
      },
    officeConnection(variables?: OfficeConnectionQueryVariables, options?: C): Promise<{data: OfficeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OfficeConnectionQueryVariables, query: string}> {
        return requester<{data: OfficeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OfficeConnectionQueryVariables, query: string}, OfficeConnectionQueryVariables>(OfficeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  